pipeline {
    agent any
	
    environment {
	DOCKER_IMAGE = 'go-image-fromjenkins'
	DOCKER_TAG = 'latest'
	KUBE_NAMESPACE = 'default'
    }

    stages {
    	stage('Setup Minikube Docker Environment') {
	    steps {
		script {
		    sh """
		    eval \$(minikube docker-env)
		    """
		}
	    }
	}
	
        stage('Build Docker Image') {
            steps {
                script {
                    sh """
		    docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ./webapi
		    """
                }
            }
        }

	stage('Deploy to Minikube') {
	    steps {
		script {
		    sh """
		    kubectl apply -f webapi/k8s/deployment.yaml --namespace=${KUBE_NAMESPACE}
		    """
		}
	    }
	}
    }
}
