pipeline {
    agent any
	
    environment {
	DOCKER_IMAGE = 'go-image-fromjenkins'
	DOCKER_TAG = 'latest'
    }

    stages {
        stage('Create Namespace') {
	    steps {
		script {
		    catchError {
		        sh 'kubectl create namespace development'
		    }
		}
	    }
	}

	stage('Build Docker Image') {
            steps {
                script {
                    sh 'eval $(minikube -p minikube docker-env) && docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ./webapi'
                }
            }
        }

	stage('Deploy to Minikube') {
	    steps {
		script {
		    sh """
		    kubectl apply -f webapi/k8s/deployment.yaml
		    """
		}
	    }
	}
    }
}
